// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM7UQgPVtI1u31VLp4SVlsxrzUfzu2Ny0',
    appId: '1:530624009783:web:4398ea543a53cffd58d1b2',
    messagingSenderId: '530624009783',
    projectId: 'song-book-83ea4',
    authDomain: 'song-book-83ea4.firebaseapp.com',
    storageBucket: 'song-book-83ea4.appspot.com',
    measurementId: 'G-MEKBXDD3WJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQailom_QycScQGQ79QKgIQoXe4KRJOX0',
    appId: '1:530624009783:android:012edc96ba2171e658d1b2',
    messagingSenderId: '530624009783',
    projectId: 'song-book-83ea4',
    storageBucket: 'song-book-83ea4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGGAGEVrGjNSLRWSVdashpbHh2EKfPdKo',
    appId: '1:530624009783:ios:20262fefb6d7dc9758d1b2',
    messagingSenderId: '530624009783',
    projectId: 'song-book-83ea4',
    storageBucket: 'song-book-83ea4.appspot.com',
    iosBundleId: 'app.web.song-book-83ea4',
  );
}
